apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: vdvrud/needwing-user-service
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: vdvrud/needwing-store-service
      context: stores
      # context is the directory containing the files
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: vdvrud/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.js'
    #         dest: .
    # - image: vdvrud/orders
    #   context: orders
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: vdvrud/orders
    #   context: orders
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: vdvrud/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: vdvrud/payments
    #   context: payments
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
