apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: vdvrud/needwing-store-service
          env:
            # - name: MONGO_URI
            #   value: 'mongodb://user-mongo-srv:27017/user'
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: needwing
---
apiVersion: v1
kind: Service
metadata:
  name: store-srv
spec:
  selector:
    app: store
  ports:
    - name: store
      protocol: TCP
      port: 5000
      targetPort: 5000
